export const countries = [
  { name: 'Afghanistan', code: 'af' },
  { name: 'Albanie', code: 'al' },
  { name: 'Algerije', code: 'dz' },
  { name: 'Andorra', code: 'ad' },
  { name: 'Angola', code: 'ao' },
  { name: 'Antigua en Barbuda', code: 'ag' },
  { name: 'Argentinie', code: 'ar' },
  { name: 'Armenie', code: 'am' },
  { name: 'Australie', code: 'au' },
  { name: 'Azerbeidzjan', code: 'az' },
  { name: 'Bahama\'s', code: 'bs' },
  { name: 'Bahrein', code: 'bh' },
  { name: 'Bangladesh', code: 'bd' },
  { name: 'Barbados', code: 'bb' },
  { name: 'Belgie', code: 'be' },
  { name: 'Belize', code: 'bz' },
  { name: 'Benin', code: 'bj' },
  { name: 'Bhutan', code: 'bt' },
  { name: 'Bolivia', code: 'bo' },
  { name: 'Bosnie en Herzegovina', code: 'ba' },
  { name: 'Botswana', code: 'bw' },
  { name: 'Brazilie', code: 'br' },
  { name: 'Brunei', code: 'bn' },
  { name: 'Bulgarije', code: 'bg' },
  { name: 'Burkina Faso', code: 'bf' },
  { name: 'Burundi', code: 'bi' },
  { name: 'Cambodja', code: 'kh' },
  { name: 'Canada', code: 'ca' },
  { name: 'Centraal-Afrikaanse Republiek', code: 'cf' },
  { name: 'Chili', code: 'cl' },
  { name: 'China', code: 'cn' },
  { name: 'Colombia', code: 'co' },
  { name: 'Comoren', code: 'km' },
  { name: 'Congo-Brazzaville', code: 'cg' },
  { name: 'Congo-Kinshasa', code: 'cd' },
  { name: 'Costa Rica', code: 'cr' },
  { name: 'Cuba', code: 'cu' },
  { name: 'Cyprus', code: 'cy' },
  { name: 'Denemarken', code: 'dk' },
  { name: 'Djibouti', code: 'dj' },
  { name: 'Dominica', code: 'dm' },
  { name: 'Dominicaanse Republiek', code: 'do' },
  { name: 'Duitsland', code: 'de' },
  { name: 'Ecuador', code: 'ec' },
  { name: 'Egypte', code: 'eg' },
  { name: 'El Salvador', code: 'sv' },
  { name: 'Equatoriaal-Guinea', code: 'gq' },
  { name: 'Eritrea', code: 'er' },
  { name: 'Estland', code: 'ee' },
  { name: 'Eswatini', code: 'sz' },
  { name: 'Ethiopie', code: 'et' },
  { name: 'Fiji', code: 'fj' },
  { name: 'Filipijnen', code: 'ph' },
  { name: 'Finland', code: 'fi' },
  { name: 'Frankrijk', code: 'fr' },
  { name: 'Gabon', code: 'ga' },
  { name: 'Gambia', code: 'gm' },
  { name: 'Georgie', code: 'ge' },
  { name: 'Ghana', code: 'gh' },
  { name: 'Grenada', code: 'gd' },
  { name: 'Griekenland', code: 'gr' },
  { name: 'Guatemala', code: 'gt' },
  { name: 'Guinee', code: 'gn' },
  { name: 'Guinee-Bissau', code: 'gw' },
  { name: 'Guyana', code: 'gy' },
  { name: 'Haiti', code: 'ht' },
  { name: 'Honduras', code: 'hn' },
  { name: 'Hongarije', code: 'hu' },
  { name: 'Ierland', code: 'ie' },
  { name: 'IJsland', code: 'is' },
  { name: 'India', code: 'in' },
  { name: 'Indonesie', code: 'id' },
  { name: 'Irak', code: 'iq' },
  { name: 'Iran', code: 'ir' },
  { name: 'Israel', code: 'il' },
  { name: 'Italie', code: 'it' },
  { name: 'Ivoorkust', code: 'ci' },
  { name: 'Jamaica', code: 'jm' },
  { name: 'Japan', code: 'jp' },
  { name: 'Jemen', code: 'ye' },
  { name: 'Jordanie', code: 'jo' },
  { name: 'Kaapverdie', code: 'cv' },
  { name: 'Kameroen', code: 'cm' },
  { name: 'Kazachstan', code: 'kz' },
  { name: 'Kenia', code: 'ke' },
  { name: 'Kirgizie', code: 'kg' },
  { name: 'Kiribati', code: 'ki' },
  { name: 'Koeweit', code: 'kw' },
  { name: 'Kroatie', code: 'hr' },
  { name: 'Laos', code: 'la' },
  { name: 'Lesotho', code: 'ls' },
  { name: 'Letland', code: 'lv' },
  { name: 'Libanon', code: 'lb' },
  { name: 'Liberia', code: 'lr' },
  { name: 'Libie', code: 'ly' },
  { name: 'Liechtenstein', code: 'li' },
  { name: 'Litouwen', code: 'lt' },
  { name: 'Luxemburg', code: 'lu' },
  { name: 'Madagaskar', code: 'mg' },
  { name: 'Malawi', code: 'mw' },
  { name: 'Maldiven', code: 'mv' },
  { name: 'Maleisie', code: 'my' },
  { name: 'Mali', code: 'ml' },
  { name: 'Malta', code: 'mt' },
  { name: 'Marokko', code: 'ma' },
  { name: 'Marshalleilanden', code: 'mh' },
  { name: 'Mauritanie', code: 'mr' },
  { name: 'Mauritius', code: 'mu' },
  { name: 'Mexico', code: 'mx' },
  { name: 'Micronesia', code: 'fm' },
  { name: 'Moldavie', code: 'md' },
  { name: 'Monaco', code: 'mc' },
  { name: 'Mongolie', code: 'mn' },
  { name: 'Montenegro', code: 'me' },
  { name: 'Mozambique', code: 'mz' },
  { name: 'Myanmar', code: 'mm' },
  { name: 'Namibie', code: 'na' },
  { name: 'Nauru', code: 'nr' },
  { name: 'Nederland', code: 'nl' },
  { name: 'Nepal', code: 'np' },
  { name: 'Nicaragua', code: 'ni' },
  { name: 'Nieuw-Zeeland', code: 'nz' },
  { name: 'Niger', code: 'ne' },
  { name: 'Nigeria', code: 'ng' },
  { name: 'Noord-Korea', code: 'kp' },
  { name: 'Noord-Macedonie', code: 'mk' },
  { name: 'Noorwegen', code: 'no' },
  { name: 'Oeganda', code: 'ug' },
  { name: 'Oekraine', code: 'ua' },
  { name: 'Oezbekistan', code: 'uz' },
  { name: 'Oman', code: 'om' },
  { name: 'Oostenrijk', code: 'at' },
  { name: 'Oost-Timor', code: 'tl' },
  { name: 'Pakistan', code: 'pk' },
  { name: 'Palau', code: 'pw' },
  { name: 'Palestina', code: 'ps' },
  { name: 'Panama', code: 'pa' },
  { name: 'Papoea-Nieuw-Guinea', code: 'pg' },
  { name: 'Paraguay', code: 'py' },
  { name: 'Peru', code: 'pe' },
  { name: 'Polen', code: 'pl' },
  { name: 'Portugal', code: 'pt' },
  { name: 'Qatar', code: 'qa' },
  { name: 'Roemenie', code: 'ro' },
  { name: 'Rusland', code: 'ru' },
  { name: 'Rwanda', code: 'rw' },
  { name: 'Saint Kitts en Nevis', code: 'kn' },
  { name: 'Saint Lucia', code: 'lc' },
  { name: 'Saint Vincent en de Grenadines', code: 'vc' },
  { name: 'Salomonseilanden', code: 'sb' },
  { name: 'Samoa', code: 'ws' },
  { name: 'San Marino', code: 'sm' },
  { name: 'Sao Tome en Principe', code: 'st' },
  { name: 'Saoedi-Arabie', code: 'sa' },
  { name: 'Senegal', code: 'sn' },
  { name: 'Servie', code: 'rs' },
  { name: 'Seychellen', code: 'sc' },
  { name: 'Sierra Leone', code: 'sl' },
  { name: 'Singapore', code: 'sg' },
  { name: 'Slovenie', code: 'si' },
  { name: 'Slowakije', code: 'sk' },
  { name: 'Soedan', code: 'sd' },
  { name: 'Somalie', code: 'so' },
  { name: 'Spanje', code: 'es' },
  { name: 'Sri Lanka', code: 'lk' },
  { name: 'Suriname', code: 'sr' },
  { name: 'Syrie', code: 'sy' },
  { name: 'Tadzjikistan', code: 'tj' },
  { name: 'Tanzania', code: 'tz' },
  { name: 'Thailand', code: 'th' },
  { name: 'Togo', code: 'tg' },
  { name: 'Tonga', code: 'to' },
  { name: 'Trinidad en Tobago', code: 'tt' },
  { name: 'Tsjaad', code: 'td' },
  { name: 'Tsjechie', code: 'cz' },
  { name: 'Tunesie', code: 'tn' },
  { name: 'Turkije', code: 'tr' },
  { name: 'Turkmenistan', code: 'tm' },
  { name: 'Tuvalu', code: 'tv' },
  { name: 'Uruguay', code: 'uy' },
  { name: 'Vanuatu', code: 'vu' },
  { name: 'Vaticaanstad', code: 'va' },
  { name: 'Venezuela', code: 've' },
  { name: 'Verenigde Arabische Emiraten', code: 'ae' },
  { name: 'Verenigde Staten', code: 'us' },
  { name: 'Verenigd Koninkrijk', code: 'gb' },
  { name: 'Vietnam', code: 'vn' },
  { name: 'Wit-Rusland', code: 'by' },
  { name: 'Zambia', code: 'zm' },
  { name: 'Zimbabwe', code: 'zw' },
  { name: 'Zuid-Afrika', code: 'za' },
  { name: 'Zuid-Korea', code: 'kr' },
  { name: 'Zuid-Soedan', code: 'ss' },
  { name: 'Zweden', code: 'se' },
  { name: 'Zwitserland', code: 'ch' },
]

